source = ~/.config/hypr/monitor.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/binds.conf

#AUTOSTART
exec-once = waybar & hyprpaper
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = flatpak run com.core447.StreamController -b

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

# permission = /usr/(bin|local/bin)/grim, screencopy, allow
# permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
# permission = /usr/(bin|local/bin)/hyprpm, plugin, allow

input {
    kb_layout = us, ru
    kb_variant =
    kb_model =
    kb_options = grp:alt_shift_toggle
    kb_rules =
    follow_mouse = 1
    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
    touchpad {
        natural_scroll = false
    }
}

device {
    name = -------ajazz-2.4g-8k
    sensitivity = -0.3
    accel_profile = flat
}

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

# Window rules per app
windowrule = match:class ^(com.core447.StreamController)$, float 1, center 1, size 900 650

# Waybar in .config/waybar
